name: 🚀 Release Library

on:
  workflow_dispatch:
    inputs:
      publish-only:
        description: "Publish only without creating a release"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      increment:
        description: "Version increment type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
      dry-run:
        description: "Run release-it in dry-run mode"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: 📥 Setup Actions
        uses: konncojs/action-pnpm-ci@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configure-npmrc: "false"

      - name: 🚀 Publishing to npm
        if: ${{ github.event.inputs.publish-only == 'true' }}
        run: pnpm publish --access public --no-git-checks

      - name: 🚀 Run release-it with manual increment
        if: ${{ github.event.inputs.publish-only == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CMD="pnpm release ${{ github.event.inputs.increment }} --ci"
          if [ "${{ github.event.inputs['dry-run'] }}" = "true" ]; then
            CMD="$CMD --dry-run"
          fi
          echo "Running command: $CMD"
          $CMD
